cast_site:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: cast
          domain: media_player
    url:
      required: true
      example: https://example.com
      selector:
        text:
